services:
  - type: web
    name: audeasy
    env: python
    repo: https://github.com/agencykhuba/AudEasy
    plan: free
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT code.app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: audeasy-db
          property: connectionString
databases:
  - name: audeasy-db
    plan: free
