name: CI Pipeline
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gaelRafa@91072834
          POSTGRES_DB: audeasy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 20
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Wait for PostgreSQL
      run: |
        for i in {1..120}; do
          if pg_isready -h localhost -p 5432 -U postgres; then
            echo "PostgreSQL is ready!"
            break
          fi
          echo "Waiting for PostgreSQL... ($i/120)"
          sleep 1
        done
        if ! pg_isready -h localhost -p 5432 -U postgres; then
          echo "PostgreSQL not ready after 120s"
          exit 1
        fi
    - name: Apply database schema
      run: |
        psql -h localhost -U postgres -d audeasy -f documents/database_schema.sql
      env:
        PGPASSWORD: gaelRafa@91072834
    - name: Insert test user
      run: python code/insert_test_user.py
      env:
        PGPASSWORD: gaelRafa@91072834
    - name: Run tests
      run: pytest code/tests.py -v
      env:
        PGPASSWORD: gaelRafa@91072834