name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: gaelRafa@91072834
          POSTGRES_DB: audeasy
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Apply database schema
      run: |
        psql -h localhost -U postgres -d audeasy -f Documents/database_schema.sql
      env:
        PGPASSWORD: gaelRafa@91072834
    - name: Insert test user
      run: python Code/insert_test_user.py
      env:
        PGPASSWORD: gaelRafa@91072834
    - name: Run tests
      run: pytest Code/tests.py -v
      env:
        PGPASSWORD: gaelRafa@91072834